version: "3.8"

services:
  db:
    image: mysql:latest
    container_name: mysql_db
    restart: always
    ports:
      - "3306:3306" # Corrected port mapping for MySQL
    environment:
      MYSQL_ROOT_PASSWORD: example_root_password
      MYSQL_DATABASE: your_database_name
      MYSQL_USER: your_username
      MYSQL_PASSWORD: your_password
